// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __diffusr_h__
#define __diffusr_h__

#include "diffusr_RcppExports.h"

#endif // __diffusr_h__
