# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Column normalize a matrix, so that it is stochastic.
#'
#' @noRd
#' @param W  the adjacency matrix to be normalized
#' @return  returns the normalized matrix
do_stoch_col_norm <- function(W) {
    .Call('diffusr_do_stoch_col_norm', PACKAGE = 'diffusr', W)
}

#' Do a Markon random walk (with restart) on an column-normalized adjacency matrix.
#'
#' @noRd
#' @param p0  the staring distribution
#' @param W  the column normalized adjacency matrix
#' @param r  restart probability
#' @return  returns the stationary distribution p_inf
do_mrwr <- function(p0, W, r) {
    .Call('diffusr_do_mrwr', PACKAGE = 'diffusr', p0, W, r)
}

#' Do a Markon random walk (with restart) on an column-normalized adjacency matrix.
#'
#' @noRd
#' @param node_idxs  the staring distribution
#' @param W  adjacency matrix
#' @param k  the depth of the nearest neighbor search
#' @param use_edge_weights  boolean flags if the edge weights should be considered when doing nearest neighbor lookup
#' @return  returns a list of nearest neighbors for every node idxs given in <emph>node_idxs</emph>
do_neighbors <- function(node_idxs, W, k, use_edge_weights) {
    .Call('diffusr_do_neighbors', PACKAGE = 'diffusr', node_idxs, W, k, use_edge_weights)
}

